# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-04 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0007_auto_20210204_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='title',
            new_name='location',
        ),
    ]
