# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-04 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0009_auto_20210204_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='names',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
