# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-04 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebapp', '0010_auto_20210204_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_email',
            new_name='owner_email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_description',
            new_name='owner_feedback',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='owner_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='admin',
        ),
    ]
